version: '3.8'
services:
  beg:
    build:
      context: ./Docker
    ports:
      - 9999:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - 3307=3306
  db:
    image: mariadb:latest
    environment:
      MYSQL_USER: ---
      MYSQL_DATABASE: ---
      MYSQL_PASSWORD: ---
      MYSQL_ROOT_PASSWORD: --
    volumes:
      - db-data:/var/lib/mysql
      - ./Docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
      - ./volumes/data/mariadb:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
volumes:
  db-data:
